#!/usr/bin/env bash
# Install the Headroom proxy, the CLI, and the Claude Code wrapper.
#
# Everything machine-specific is generated here, so nothing has to be edited by
# hand afterwards. Written for bash 3.2 — macOS still ships that, and this
# script is what installs a newer one.
set -euo pipefail

REPO_DIR=$(cd "$(dirname "$0")" && pwd)
DIST="$REPO_DIR/dist"
BIN_DIR="$HOME/.local/bin"
CLAUDE_DIR="$HOME/.claude"
FLAGS_FILE="$HOME/.headroom-flags.sh"
PATHS_FILE="$HOME/.headroom-paths.sh"
SETTINGS="$CLAUDE_DIR/settings.json"
OS=$(uname -s)
BUILD=1

for arg in "$@"; do
    case "$arg" in
        --no-build) BUILD=0 ;;
        -h|--help)
            echo "usage: ./install.sh [--no-build]"
            exit 0 ;;
        *) echo "unknown option: $arg" >&2; exit 2 ;;
    esac
done

say() { printf '  %s\n' "$*"; }
step() { printf '\n== %s\n' "$*"; }

# ── dependencies ──────────────────────────────────────────────────────────
# The scripts use GNU tools that macOS either ships too old (bash 3.2, no
# associative arrays) or not at all (setsid, stat -c, grep -oP, ss).
step "Dependencies"
if [ "$OS" = "Darwin" ]; then
    if ! command -v brew >/dev/null 2>&1; then
        echo "Homebrew is required on macOS: https://brew.sh" >&2
        exit 1
    fi
    say "installing bash, grep, coreutils, util-linux, iproute2mac, jq"
    brew install bash grep coreutils util-linux iproute2mac jq

    BREW_PREFIX=$(brew --prefix)
    cat > "$PATHS_FILE" <<EOF
# Generated by headroom install.sh — do not edit, it is rewritten on install.
# Puts the GNU tools ahead of the macOS ones for scripts that source this.
export PATH="$BREW_PREFIX/opt/coreutils/libexec/gnubin:$BREW_PREFIX/opt/grep/libexec/gnubin:$BREW_PREFIX/opt/util-linux/bin:$BREW_PREFIX/opt/util-linux/sbin:\$PATH"
export HEADROOM_REPO="$REPO_DIR"
EOF
    say "wrote $PATHS_FILE"

    # claude-launcher uses an associative array, so it needs bash 4+. Homebrew
    # installs one, but `#!/usr/bin/env bash` still picks the 3.2 in /bin unless
    # the Homebrew path comes first. Silent failure otherwise, on line 57.
    BASH_MAJOR=$(bash -c 'echo ${BASH_VERSINFO[0]}')
    if [ "$BASH_MAJOR" -lt 4 ]; then
        say "WARNING: 'bash' still resolves to $BASH_MAJOR.x — cclaude will fail."
        say "         Put $BREW_PREFIX/bin ahead of /bin in your PATH and reopen the shell."
    fi
else
    say "Linux — GNU tools are already the system ones"
    printf 'export HEADROOM_REPO="%s"\n' "$REPO_DIR" > "$PATHS_FILE"
fi

for tool in jq lsof; do
    command -v "$tool" >/dev/null 2>&1 || say "WARNING: $tool not found — install it, the status line and restart script need it"
done

# ── binaries ──────────────────────────────────────────────────────────────
step "Binaries"
mkdir -p "$BIN_DIR"
if [ "$BUILD" = 1 ]; then
    command -v cargo >/dev/null 2>&1 || {
        echo "cargo not found. Install Rust (https://rustup.rs) or pass --no-build" >&2
        exit 1
    }
    say "building release binaries (a few minutes on a cold cache)"
    ( cd "$REPO_DIR" && cargo build --release -p headroom-proxy )
fi
for bin in headroom-proxy headroom; do
    src="$REPO_DIR/target/release/$bin"
    [ -x "$src" ] || { echo "missing $src — run without --no-build" >&2; exit 1; }
    install -m 755 "$src" "$BIN_DIR/$bin"
    say "installed $BIN_DIR/$bin"
done

# ── flag set ──────────────────────────────────────────────────────────────
# The measured settings, with paths resolved for this machine. An existing file
# is kept: it may hold tuning worth more than this default.
step "Flags"
if [ -f "$FLAGS_FILE" ]; then
    say "$FLAGS_FILE exists — left alone (delete it to regenerate)"
else
    CODEX_AUTH=""
    for candidate in "$HOME/.codex/auth.json" "$HOME/.codex-personal/auth.json"; do
        [ -f "$candidate" ] && CODEX_AUTH="$candidate" && break
    done

    {
        echo "# Generated by headroom install.sh on $(date '+%Y-%m-%d')."
        echo "# The measured flag set. Both claude-launcher and restart-headroom.sh"
        echo "# source this, so a change here applies to whichever starts the proxy."
        echo "HEADROOM_FLAGS=("
        echo "  --memory true"
        echo "  --ctx-store-dir \"\$HOME/.claude-personal/context-mode\""
        echo "  --ctx-offload-min-bytes 15000"
        echo "  --compression-mode all_messages"
        echo "  --prefix-replay true"
        echo "  --cache-tail-breakpoints 2"
        echo "  --strip-system-cache-breakpoints false"
        echo "  --enable-cross-turn-dedup"
        echo "  --force-1h-cache-ttl true"
        if [ -n "$CODEX_AUTH" ]; then
            echo "  --extra-model-route claude-codex-5.6-luna=https://api.openai.com/:translate:gpt-5.6-luna"
            echo "  --extra-model-route claude-codex-5.6-terra=https://api.openai.com/:translate:gpt-5.6-terra"
            echo "  --extra-model-route claude-codex-5.6-sol=https://api.openai.com/:translate:gpt-5.6-sol"
            echo "  --codex-auth-file \"$CODEX_AUTH\""
        else
            echo "  # No Codex auth file found. To reach Codex models from inside"
            echo "  # Claude Code, log in with the Codex CLI and re-run this script."
        fi
        echo ")"
    } > "$FLAGS_FILE"
    say "wrote $FLAGS_FILE${CODEX_AUTH:+ (Codex routes on, auth at $CODEX_AUTH)}"
fi

# ── launcher ──────────────────────────────────────────────────────────────
step "Launcher"
install -m 755 "$DIST/claude-launcher" "$BIN_DIR/claude-launcher"
ln -sf claude-launcher "$BIN_DIR/cclaude"
install -m 755 "$DIST/restart-headroom.sh" "$BIN_DIR/restart-headroom.sh"
say "installed cclaude -> claude-launcher, and restart-headroom.sh"

case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) say "WARNING: $BIN_DIR is not on your PATH — add it to your shell profile" ;;
esac

# ── status line ───────────────────────────────────────────────────────────
# The checkout path is baked into the installed copy: Claude Code runs the
# status line without this script's environment, so a variable would be empty.
step "Status line"
mkdir -p "$CLAUDE_DIR"
install -m 755 "$DIST/statusline-usage-dump.sh" "$CLAUDE_DIR/statusline-usage-dump.sh"
sed "s|\${HEADROOM_REPO:-\$HOME/headroom}|$REPO_DIR|g" \
    "$DIST/statusline-with-cache.sh" > "$CLAUDE_DIR/statusline-with-cache.sh"
chmod 755 "$CLAUDE_DIR/statusline-with-cache.sh"

if command -v node >/dev/null 2>&1; then
    [ -f "$SETTINGS" ] && cp "$SETTINGS" "$SETTINGS.bak"
    node -e '
const fs = require("fs");
const [file, cmd] = process.argv.slice(1);
let settings = {};
try { settings = JSON.parse(fs.readFileSync(file, "utf8")); } catch (e) {}
settings.statusLine = { type: "command", command: cmd };
fs.writeFileSync(file, JSON.stringify(settings, null, 2) + "\n");
' "$SETTINGS" "$CLAUDE_DIR/statusline-with-cache.sh"
    say "status line wired into $SETTINGS"
else
    say "node not found — set statusLine.command in $SETTINGS by hand:"
    say "  $CLAUDE_DIR/statusline-with-cache.sh"
fi

# ── done ──────────────────────────────────────────────────────────────────
step "Done"
say "Start Claude Code with:  cclaude"
say "Check it is working:     headroom doctor"
say "See what it saved:       headroom savings"
say ""
say "To go back: run 'claude' instead, and 'pkill -f headroom-proxy'."
