#!/usr/bin/env bash
# Install the Headroom proxy, the CLI, and the Claude Code wrapper.
#
# Everything machine-specific is generated here, so nothing has to be edited by
# hand afterwards. Written for bash 3.2 — macOS still ships that, and this
# script is what installs a newer one.
set -euo pipefail

REPO_DIR=$(cd "$(dirname "$0")" && pwd)
CONTRIB="$REPO_DIR/contrib"
BIN_DIR="$HOME/.local/bin"
CLAUDE_DIR="$HOME/.claude"
FLAGS_FILE="$HOME/.headroom-flags.sh"
PATHS_FILE="$HOME/.headroom-paths.sh"
SETTINGS="$CLAUDE_DIR/settings.json"
OS=$(uname -s)
BUILD=1
LINK=0
HOOKS_INTO="$HOME"

while [ $# -gt 0 ]; do
    case "$1" in
        --no-build) BUILD=0 ;;
        --link) LINK=1 ;;
        --hooks-into) HOOKS_INTO="${2:?--hooks-into needs a directory}"; shift ;;
        --hooks-into=*) HOOKS_INTO="${1#*=}" ;;
        -h|--help)
            echo "usage: ./install.sh [--no-build] [--link] [--hooks-into DIR]"
            echo "  --no-build     skip cargo build; install whatever target/release holds"
            echo "  --link         symlink the scripts and flags file into the checkout,"
            echo "                 so editing the repo edits the live setup"
            echo "  --hooks-into   project whose sessions should run the review hooks"
            echo "                 (default: \$HOME, i.e. every session on this machine)"
            exit 0 ;;
        *) echo "unknown option: $1" >&2; exit 2 ;;
    esac
    shift
done

# Where the review hooks get REGISTERED. The scripts themselves always install
# to ~/.claude/hooks -- one copy, one path in every settings file. Only the
# registration moves, because that is what decides which sessions pay for them.
#
# Registering at $HOME runs review-gate on every prompt and every Bash, Write
# and Edit in every project on the machine. That is right only if reviews start
# from anywhere. When the slash commands that arm it live in one repo, the hook
# can never fire usefully elsewhere and a bug in it takes out every session
# instead of one project's.
#
# Project targets get settings.local.json, not settings.json: the latter is
# checked in, and switching on automated tracker writes for everyone who clones
# the repo is not a thing an installer should do quietly.
if [ "$HOOKS_INTO" = "$HOME" ]; then
    HOOK_SETTINGS="$CLAUDE_DIR/settings.json"
    HOOK_PRUNE=""
else
    HOOKS_INTO=$(cd "$HOOKS_INTO" 2>/dev/null && pwd) ||
        { echo "--hooks-into: no such directory" >&2; exit 2; }
    HOOK_SETTINGS="$HOOKS_INTO/.claude/settings.local.json"
    # Anything left behind at user level would keep firing everywhere, so the
    # move is a move rather than a copy.
    HOOK_PRUNE="$CLAUDE_DIR/settings.json"
fi

say() { printf '  %s\n' "$*"; }
step() { printf '\n== %s\n' "$*"; }

# ── dependencies ──────────────────────────────────────────────────────────
# The scripts use GNU tools that macOS either ships too old (bash 3.2, no
# associative arrays) or not at all (setsid, stat -c, grep -oP, ss).
step "Dependencies"
if [ "$OS" = "Darwin" ]; then
    if ! command -v brew >/dev/null 2>&1; then
        echo "Homebrew is required on macOS: https://brew.sh" >&2
        exit 1
    fi
    say "installing bash, grep, coreutils, util-linux, iproute2mac, jq"
    brew install bash grep coreutils util-linux iproute2mac jq

    BREW_PREFIX=$(brew --prefix)
    cat > "$PATHS_FILE" <<EOF
# Generated by headroom install.sh — do not edit, it is rewritten on install.
# Puts the GNU tools ahead of the macOS ones for scripts that source this.
export PATH="$BREW_PREFIX/opt/coreutils/libexec/gnubin:$BREW_PREFIX/opt/grep/libexec/gnubin:$BREW_PREFIX/opt/util-linux/bin:$BREW_PREFIX/opt/util-linux/sbin:\$PATH"
export HEADROOM_REPO="$REPO_DIR"
EOF
    say "wrote $PATHS_FILE"

    # claude-launcher uses an associative array, so it needs bash 4+. Homebrew
    # installs one, but `#!/usr/bin/env bash` still picks the 3.2 in /bin unless
    # the Homebrew path comes first. Silent failure otherwise, on line 57.
    BASH_MAJOR=$(bash -c 'echo ${BASH_VERSINFO[0]}')
    if [ "$BASH_MAJOR" -lt 4 ]; then
        say "WARNING: 'bash' still resolves to $BASH_MAJOR.x — cclaude will fail."
        say "         Put $BREW_PREFIX/bin ahead of /bin in your PATH and reopen the shell."
    fi
else
    say "Linux — GNU tools are already the system ones"
    printf 'export HEADROOM_REPO="%s"\n' "$REPO_DIR" > "$PATHS_FILE"
fi

for tool in jq lsof; do
    command -v "$tool" >/dev/null 2>&1 || say "WARNING: $tool not found — install it, the status line and restart script need it"
done

# ── binaries ──────────────────────────────────────────────────────────────
step "Binaries"
mkdir -p "$BIN_DIR"
if [ "$BUILD" = 1 ]; then
    command -v cargo >/dev/null 2>&1 || {
        echo "cargo not found. Install Rust (https://rustup.rs) or pass --no-build" >&2
        exit 1
    }
    say "building release binaries (a few minutes on a cold cache)"
    ( cd "$REPO_DIR" && cargo build --release -p headroom-proxy )
fi
for bin in headroom-proxy headroom; do
    src="$REPO_DIR/target/release/$bin"
    [ -x "$src" ] || { echo "missing $src — run without --no-build" >&2; exit 1; }
    install -m 755 "$src" "$BIN_DIR/$bin"
    say "installed $BIN_DIR/$bin"
done

# ── flag set ──────────────────────────────────────────────────────────────
# contrib/headroom-flags.sh is the measured flag set — every option the
# maintainer runs with, paths written as $HOME. An existing file is kept: it
# may hold tuning worth more than this default. With --link the home file is
# a symlink into the checkout, so editing either edits the live setup.
step "Flags"
if [ -L "$FLAGS_FILE" ] && [ "$(readlink "$FLAGS_FILE")" = "$CONTRIB/headroom-flags.sh" ]; then
    say "$FLAGS_FILE already links into the checkout"
elif [ -e "$FLAGS_FILE" ] && [ "$LINK" = 0 ]; then
    say "$FLAGS_FILE exists — left alone (delete it to regenerate)"
elif [ "$LINK" = 1 ]; then
    [ -e "$FLAGS_FILE" ] && [ ! -L "$FLAGS_FILE" ] && mv "$FLAGS_FILE" "$FLAGS_FILE.bak" \
        && say "moved the old $FLAGS_FILE to $FLAGS_FILE.bak"
    ln -sfn "$CONTRIB/headroom-flags.sh" "$FLAGS_FILE"
    say "linked $FLAGS_FILE -> $CONTRIB/headroom-flags.sh"
else
    cp "$CONTRIB/headroom-flags.sh" "$FLAGS_FILE"
    say "wrote $FLAGS_FILE from contrib/headroom-flags.sh"
fi

# The Codex routes need a Codex CLI login. Point the flag at whichever
# auth.json exists; otherwise drop it so the proxy starts without it.
CODEX_AUTH=""
for candidate in "$HOME/.codex/auth.json" "$HOME/.codex-personal/auth.json"; do
    [ -f "$candidate" ] && CODEX_AUTH="$candidate" && break
done
if [ "$LINK" = 0 ] && grep -q -- '--codex-auth-file' "$FLAGS_FILE"; then
    if [ -n "$CODEX_AUTH" ]; then
        sed -i.tmp "s|--codex-auth-file .*|--codex-auth-file \"$CODEX_AUTH\"|" "$FLAGS_FILE" && rm -f "$FLAGS_FILE.tmp"
        say "Codex routes on, auth at $CODEX_AUTH"
    else
        sed -i.tmp 's|^\(\s*\)--codex-auth-file|\1# --codex-auth-file|' "$FLAGS_FILE" && rm -f "$FLAGS_FILE.tmp"
        say "no Codex auth.json found — --codex-auth-file commented out; log in with the Codex CLI and re-run to enable"
    fi
elif [ "$LINK" = 1 ] && [ -z "$CODEX_AUTH" ]; then
    say "WARNING: flags reference --codex-auth-file but no ~/.codex*/auth.json exists; edit contrib/headroom-flags.sh"
fi

# ── ONNX Runtime ─────────────────────────────────────────────────────────
# The `ml` feature (on by default) loads libonnxruntime at startup for file
# type detection and embeddings. It is found via ORT_DYLIB_PATH or a Python
# onnxruntime package. Without it the proxy still starts; those transforms
# log a warning and step aside.
step "ONNX Runtime"
if [ -n "${ORT_DYLIB_PATH:-}" ] && [ -f "$ORT_DYLIB_PATH" ]; then
    say "ORT_DYLIB_PATH=$ORT_DYLIB_PATH"
elif python3 -c 'import onnxruntime' >/dev/null 2>&1; then
    say "python onnxruntime package found"
else
    say "not found — optional. For Magika file detection and embeddings:"
    say "  pip install onnxruntime   (or set ORT_DYLIB_PATH to libonnxruntime.so)"
fi

# ── launcher ──────────────────────────────────────────────────────────────
step "Launcher"
if [ "$LINK" = 1 ]; then
    ln -sfn "$CONTRIB/claude-launcher" "$BIN_DIR/claude-launcher"
    ln -sfn "$CONTRIB/restart-headroom.sh" "$BIN_DIR/restart-headroom.sh"
    say "linked claude-launcher and restart-headroom.sh into the checkout"
else
    install -m 755 "$CONTRIB/claude-launcher" "$BIN_DIR/claude-launcher"
    install -m 755 "$CONTRIB/restart-headroom.sh" "$BIN_DIR/restart-headroom.sh"
    say "installed claude-launcher and restart-headroom.sh"
fi
ln -sfn claude-launcher "$BIN_DIR/cclaude"
say "cclaude -> claude-launcher"

case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) say "WARNING: $BIN_DIR is not on your PATH — add it to your shell profile" ;;
esac

# ── status line ───────────────────────────────────────────────────────────
# The checkout path is baked into the installed copy: Claude Code runs the
# status line without this script's environment, so a variable would be empty.
step "Status line"
mkdir -p "$CLAUDE_DIR"
if [ "$LINK" = 1 ]; then
    ln -sfn "$CONTRIB/statusline-usage-dump.sh" "$CLAUDE_DIR/statusline-usage-dump.sh"
else
    install -m 755 "$CONTRIB/statusline-usage-dump.sh" "$CLAUDE_DIR/statusline-usage-dump.sh"
fi
# The wrapper finds its helper scripts (cache health, codex limits, cache
# perf) next to itself in contrib/, so the checkout has to stay where it is.
if [ "$LINK" = 1 ]; then
    [ -e "$CLAUDE_DIR/statusline-with-cache.sh" ] && [ ! -L "$CLAUDE_DIR/statusline-with-cache.sh" ] \
        && mv "$CLAUDE_DIR/statusline-with-cache.sh" "$CLAUDE_DIR/statusline-with-cache.sh.bak"
    ln -sfn "$CONTRIB/statusline-with-cache.sh" "$CLAUDE_DIR/statusline-with-cache.sh"
else
    sed "s|\${HEADROOM_REPO:-\$HOME/headroom}|$REPO_DIR|g" \
        "$CONTRIB/statusline-with-cache.sh" > "$CLAUDE_DIR/statusline-with-cache.sh"
    chmod 755 "$CLAUDE_DIR/statusline-with-cache.sh"
fi

if command -v node >/dev/null 2>&1; then
    [ -f "$SETTINGS" ] && cp "$SETTINGS" "$SETTINGS.bak"
    node -e '
const fs = require("fs");
const [file, cmd] = process.argv.slice(1);
let settings = {};
try { settings = JSON.parse(fs.readFileSync(file, "utf8")); } catch (e) {}
settings.statusLine = { type: "command", command: cmd };
fs.writeFileSync(file, JSON.stringify(settings, null, 2) + "\n");
' "$SETTINGS" "$CLAUDE_DIR/statusline-with-cache.sh"
    say "status line wired into $SETTINGS"
else
    say "node not found — set statusLine.command in $SETTINGS by hand:"
    say "  $CLAUDE_DIR/statusline-with-cache.sh"
fi

# ── Claude Code agents ────────────────────────────────────────────────────
# One subagent definition per routed model (codex-*, grok-*, spark*), so
# `Agent(subagent_type: "codex-sol")` works out of the box. A file the user
# already has under the same name is left alone.
step "Agents"
mkdir -p "$CLAUDE_DIR/agents"
for src in "$CONTRIB"/claude/agents/*.md; do
    dst="$CLAUDE_DIR/agents/$(basename "$src")"
    if [ -L "$dst" ] && [ "$(readlink "$dst")" = "$src" ]; then
        continue
    elif [ -e "$dst" ]; then
        say "$dst exists — left alone"
    elif [ "$LINK" = 1 ]; then
        ln -sfn "$src" "$dst"
    else
        install -m 644 "$src" "$dst"
    fi
done
say "agents in $CLAUDE_DIR/agents: $(ls "$CONTRIB"/claude/agents/*.md | xargs -n1 basename | sed 's/\.md$//' | tr '\n' ' ')"

# ── Claude Code hooks ─────────────────────────────────────────────────────
# Headroom-owned hook scripts (session map logger, review write-offload
# gate). Installed the same way as the launcher: copied by default,
# symlinked with --link so editing the checkout edits the live setup.
# The settings entries below are then ensured idempotently — a re-run
# never duplicates them.
step "Hooks"
mkdir -p "$CLAUDE_DIR/hooks"
for src in "$CONTRIB"/claude/hooks/*.sh; do
    dst="$CLAUDE_DIR/hooks/$(basename "$src")"
    if [ "$LINK" = 1 ]; then
        [ -e "$dst" ] && [ ! -L "$dst" ] && mv "$dst" "$dst.bak" \
            && say "moved the old $dst to $dst.bak"
        ln -sfn "$src" "$dst"
        say "linked $dst -> $src"
    else
        install -m 755 "$src" "$dst"
        say "installed $dst"
    fi
done

if command -v node >/dev/null 2>&1; then
    mkdir -p "$(dirname "$HOOK_SETTINGS")"
    [ -f "$HOOK_SETTINGS" ] && cp "$HOOK_SETTINGS" "$HOOK_SETTINGS.bak"
    [ -n "$HOOK_PRUNE" ] && [ -f "$HOOK_PRUNE" ] && cp "$HOOK_PRUNE" "$HOOK_PRUNE.bak"
    node -e '
const fs = require("fs");
const [file, dir, pruneFile] = process.argv.slice(1);

// Every event the review chain needs, in one list, so a target change moves
// all of them together. UserPromptSubmit is the one that matters: it fires on
// the go-ahead, before the diffs are read and the replies are written, which
// is the only point where diverting still saves anything.
const WANT = [
  ["UserPromptSubmit", null,                  "review-gate.sh",    10],
  ["PreToolUse",       "Bash",                "review-gate.sh",    10],
  ["PreToolUse",       "Write|Edit|MultiEdit", "review-gate.sh",   10],
  ["Stop",             null,                  "review-gate.sh",    10],
  ["SessionStart",     null,                  "session-map-log.sh", 5],
];

function load(f) { try { return JSON.parse(fs.readFileSync(f, "utf8")); } catch (e) { return {}; } }

const settings = load(file);
settings.hooks = settings.hooks || {};
function ensure(event, matcher, entry) {
  settings.hooks[event] = settings.hooks[event] || [];
  let group = settings.hooks[event].find(g => (g.matcher || null) === (matcher || null));
  if (!group) { group = matcher ? { matcher: matcher, hooks: [] } : { hooks: [] }; settings.hooks[event].push(group); }
  group.hooks = group.hooks || [];
  if (!group.hooks.some(h => h.command === entry.command)) group.hooks.push(entry);
}
for (const [event, matcher, script, timeout] of WANT) {
  ensure(event, matcher, { type: "command", command: dir + "/" + script, timeout: timeout });
}

// One registration per (event, matcher, command). A hand-added group with no
// matcher and a generated one with matcher "" both normalise to null, so
// ensure() appends to the first while the second still holds the same command
// -- and the hook then runs twice on every prompt. Matchers that genuinely
// differ are left alone: review-gate is registered for Bash and for
// Write|Edit|MultiEdit on purpose.
for (const event of Object.keys(settings.hooks)) {
  const seen = new Set();
  settings.hooks[event] = (settings.hooks[event] || []).map(g => {
    const key = (g.matcher || null) + " ";
    const keep = (g.hooks || []).filter(h => {
      if (seen.has(key + h.command)) return false;
      seen.add(key + h.command);
      return true;
    });
    return Object.assign({}, g, { hooks: keep });
  }).filter(g => (g.hooks || []).length > 0);
}
fs.writeFileSync(file, JSON.stringify(settings, null, 2) + "\n");

// Drop the same commands wherever they were registered before, or the old
// registration keeps firing in every project alongside the new one.
if (pruneFile && pruneFile !== file) {
  const mine = new Set(WANT.map(w => dir + "/" + w[2]));
  const other = load(pruneFile);
  let removed = 0;
  for (const event of Object.keys(other.hooks || {})) {
    other.hooks[event] = (other.hooks[event] || []).map(g => {
      const keep = (g.hooks || []).filter(h => !mine.has(h.command));
      removed += (g.hooks || []).length - keep.length;
      return Object.assign({}, g, { hooks: keep });
    }).filter(g => (g.hooks || []).length > 0);
    if (other.hooks[event].length === 0) delete other.hooks[event];
  }
  if (removed > 0) {
    fs.writeFileSync(pruneFile, JSON.stringify(other, null, 2) + "\n");
    console.log("  removed " + removed + " stale registration(s) from " + pruneFile);
  }
}
' "$HOOK_SETTINGS" "$CLAUDE_DIR/hooks" "$HOOK_PRUNE"
    say "hooks wired into $HOOK_SETTINGS"
    [ -n "$HOOK_PRUNE" ] &&
        say "sessions outside $HOOKS_INTO no longer run the review hooks"
else
    say "node not found — add the review-gate.sh / session-map-log.sh entries in $HOOK_SETTINGS by hand"
fi

# ── CLAUDE.md ─────────────────────────────────────────────────────────────
# The proxy injects memory tools and headroom_retrieve; this excerpt tells
# the model how to use them. Spliced between markers so a re-run replaces it.
step "CLAUDE.md"
CLAUDE_MD="$CLAUDE_DIR/CLAUDE.md"
BEGIN_MARK="<!-- headroom:begin -->"
END_MARK="<!-- headroom:end -->"
touch "$CLAUDE_MD"
if grep -qF "$BEGIN_MARK" "$CLAUDE_MD"; then
    awk -v b="$BEGIN_MARK" -v e="$END_MARK" -v f="$CONTRIB/claude/CLAUDE.headroom.md" '
        index($0,b)==1 { print; while ((getline l < f) > 0) print l; skip=1; next }
        index($0,e)==1 { skip=0 }
        !skip' "$CLAUDE_MD" > "$CLAUDE_MD.tmp" && mv "$CLAUDE_MD.tmp" "$CLAUDE_MD"
    say "refreshed the headroom section in $CLAUDE_MD"
else
    { printf '\n%s\n' "$BEGIN_MARK"; cat "$CONTRIB/claude/CLAUDE.headroom.md"; printf '%s\n' "$END_MARK"; } >> "$CLAUDE_MD"
    say "appended the headroom section to $CLAUDE_MD"
fi

# ── done ──────────────────────────────────────────────────────────────────
step "Done"
say "Start Claude Code with:  cclaude"
say "Check it is working:     headroom doctor"
say "See what it saved:       headroom savings"
say ""
say "To go back: run 'claude' instead, and 'pkill -f headroom-proxy'."
