#!/usr/bin/env bash
# Install the Headroom proxy, the CLI, and the Claude Code wrapper.
#
# Everything machine-specific is generated here, so nothing has to be edited by
# hand afterwards. Written for bash 3.2 — macOS still ships that, and this
# script is what installs a newer one.
set -euo pipefail

REPO_DIR=$(cd "$(dirname "$0")" && pwd)
CONTRIB="$REPO_DIR/contrib"
BIN_DIR="$HOME/.local/bin"
CLAUDE_DIR="$HOME/.claude"
FLAGS_FILE="$HOME/.headroom-flags.sh"
PATHS_FILE="$HOME/.headroom-paths.sh"
SETTINGS="$CLAUDE_DIR/settings.json"
OS=$(uname -s)
BUILD=1
LINK=0

for arg in "$@"; do
    case "$arg" in
        --no-build) BUILD=0 ;;
        --link) LINK=1 ;;
        -h|--help)
            echo "usage: ./install.sh [--no-build] [--link]"
            echo "  --no-build  skip cargo build; install whatever target/release holds"
            echo "  --link      symlink the scripts and flags file into the checkout,"
            echo "              so editing the repo edits the live setup"
            exit 0 ;;
        *) echo "unknown option: $arg" >&2; exit 2 ;;
    esac
done

say() { printf '  %s\n' "$*"; }
step() { printf '\n== %s\n' "$*"; }

# ── dependencies ──────────────────────────────────────────────────────────
# The scripts use GNU tools that macOS either ships too old (bash 3.2, no
# associative arrays) or not at all (setsid, stat -c, grep -oP, ss).
step "Dependencies"
if [ "$OS" = "Darwin" ]; then
    if ! command -v brew >/dev/null 2>&1; then
        echo "Homebrew is required on macOS: https://brew.sh" >&2
        exit 1
    fi
    say "installing bash, grep, coreutils, util-linux, iproute2mac, jq"
    brew install bash grep coreutils util-linux iproute2mac jq

    BREW_PREFIX=$(brew --prefix)
    cat > "$PATHS_FILE" <<EOF
# Generated by headroom install.sh — do not edit, it is rewritten on install.
# Puts the GNU tools ahead of the macOS ones for scripts that source this.
export PATH="$BREW_PREFIX/opt/coreutils/libexec/gnubin:$BREW_PREFIX/opt/grep/libexec/gnubin:$BREW_PREFIX/opt/util-linux/bin:$BREW_PREFIX/opt/util-linux/sbin:\$PATH"
export HEADROOM_REPO="$REPO_DIR"
EOF
    say "wrote $PATHS_FILE"

    # claude-launcher uses an associative array, so it needs bash 4+. Homebrew
    # installs one, but `#!/usr/bin/env bash` still picks the 3.2 in /bin unless
    # the Homebrew path comes first. Silent failure otherwise, on line 57.
    BASH_MAJOR=$(bash -c 'echo ${BASH_VERSINFO[0]}')
    if [ "$BASH_MAJOR" -lt 4 ]; then
        say "WARNING: 'bash' still resolves to $BASH_MAJOR.x — cclaude will fail."
        say "         Put $BREW_PREFIX/bin ahead of /bin in your PATH and reopen the shell."
    fi
else
    say "Linux — GNU tools are already the system ones"
    printf 'export HEADROOM_REPO="%s"\n' "$REPO_DIR" > "$PATHS_FILE"
fi

for tool in jq lsof; do
    command -v "$tool" >/dev/null 2>&1 || say "WARNING: $tool not found — install it, the status line and restart script need it"
done

# ── binaries ──────────────────────────────────────────────────────────────
step "Binaries"
mkdir -p "$BIN_DIR"
if [ "$BUILD" = 1 ]; then
    command -v cargo >/dev/null 2>&1 || {
        echo "cargo not found. Install Rust (https://rustup.rs) or pass --no-build" >&2
        exit 1
    }
    say "building release binaries (a few minutes on a cold cache)"
    ( cd "$REPO_DIR" && cargo build --release -p headroom-proxy )
fi
for bin in headroom-proxy headroom; do
    src="$REPO_DIR/target/release/$bin"
    [ -x "$src" ] || { echo "missing $src — run without --no-build" >&2; exit 1; }
    install -m 755 "$src" "$BIN_DIR/$bin"
    say "installed $BIN_DIR/$bin"
done

# ── flag set ──────────────────────────────────────────────────────────────
# contrib/headroom-flags.sh is the measured flag set — every option the
# maintainer runs with, paths written as $HOME. An existing file is kept: it
# may hold tuning worth more than this default. With --link the home file is
# a symlink into the checkout, so editing either edits the live setup.
step "Flags"
if [ -L "$FLAGS_FILE" ] && [ "$(readlink "$FLAGS_FILE")" = "$CONTRIB/headroom-flags.sh" ]; then
    say "$FLAGS_FILE already links into the checkout"
elif [ -e "$FLAGS_FILE" ] && [ "$LINK" = 0 ]; then
    say "$FLAGS_FILE exists — left alone (delete it to regenerate)"
elif [ "$LINK" = 1 ]; then
    [ -e "$FLAGS_FILE" ] && [ ! -L "$FLAGS_FILE" ] && mv "$FLAGS_FILE" "$FLAGS_FILE.bak" \
        && say "moved the old $FLAGS_FILE to $FLAGS_FILE.bak"
    ln -sfn "$CONTRIB/headroom-flags.sh" "$FLAGS_FILE"
    say "linked $FLAGS_FILE -> $CONTRIB/headroom-flags.sh"
else
    cp "$CONTRIB/headroom-flags.sh" "$FLAGS_FILE"
    say "wrote $FLAGS_FILE from contrib/headroom-flags.sh"
fi

# The Codex routes need a Codex CLI login. Point the flag at whichever
# auth.json exists; otherwise drop it so the proxy starts without it.
CODEX_AUTH=""
for candidate in "$HOME/.codex/auth.json" "$HOME/.codex-personal/auth.json"; do
    [ -f "$candidate" ] && CODEX_AUTH="$candidate" && break
done
if [ "$LINK" = 0 ] && grep -q -- '--codex-auth-file' "$FLAGS_FILE"; then
    if [ -n "$CODEX_AUTH" ]; then
        sed -i.tmp "s|--codex-auth-file .*|--codex-auth-file \"$CODEX_AUTH\"|" "$FLAGS_FILE" && rm -f "$FLAGS_FILE.tmp"
        say "Codex routes on, auth at $CODEX_AUTH"
    else
        sed -i.tmp 's|^\(\s*\)--codex-auth-file|\1# --codex-auth-file|' "$FLAGS_FILE" && rm -f "$FLAGS_FILE.tmp"
        say "no Codex auth.json found — --codex-auth-file commented out; log in with the Codex CLI and re-run to enable"
    fi
elif [ "$LINK" = 1 ] && [ -z "$CODEX_AUTH" ]; then
    say "WARNING: flags reference --codex-auth-file but no ~/.codex*/auth.json exists; edit contrib/headroom-flags.sh"
fi

# ── ONNX Runtime ─────────────────────────────────────────────────────────
# The `ml` feature (on by default) loads libonnxruntime at startup for file
# type detection and embeddings. It is found via ORT_DYLIB_PATH or a Python
# onnxruntime package. Without it the proxy still starts; those transforms
# log a warning and step aside.
step "ONNX Runtime"
if [ -n "${ORT_DYLIB_PATH:-}" ] && [ -f "$ORT_DYLIB_PATH" ]; then
    say "ORT_DYLIB_PATH=$ORT_DYLIB_PATH"
elif python3 -c 'import onnxruntime' >/dev/null 2>&1; then
    say "python onnxruntime package found"
else
    say "not found — optional. For Magika file detection and embeddings:"
    say "  pip install onnxruntime   (or set ORT_DYLIB_PATH to libonnxruntime.so)"
fi

# ── launcher ──────────────────────────────────────────────────────────────
step "Launcher"
if [ "$LINK" = 1 ]; then
    ln -sfn "$CONTRIB/claude-launcher" "$BIN_DIR/claude-launcher"
    ln -sfn "$CONTRIB/restart-headroom.sh" "$BIN_DIR/restart-headroom.sh"
    say "linked claude-launcher and restart-headroom.sh into the checkout"
else
    install -m 755 "$CONTRIB/claude-launcher" "$BIN_DIR/claude-launcher"
    install -m 755 "$CONTRIB/restart-headroom.sh" "$BIN_DIR/restart-headroom.sh"
    say "installed claude-launcher and restart-headroom.sh"
fi
ln -sfn claude-launcher "$BIN_DIR/cclaude"
say "cclaude -> claude-launcher"

case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) say "WARNING: $BIN_DIR is not on your PATH — add it to your shell profile" ;;
esac

# ── status line ───────────────────────────────────────────────────────────
# The checkout path is baked into the installed copy: Claude Code runs the
# status line without this script's environment, so a variable would be empty.
step "Status line"
mkdir -p "$CLAUDE_DIR"
if [ "$LINK" = 1 ]; then
    ln -sfn "$CONTRIB/statusline-usage-dump.sh" "$CLAUDE_DIR/statusline-usage-dump.sh"
else
    install -m 755 "$CONTRIB/statusline-usage-dump.sh" "$CLAUDE_DIR/statusline-usage-dump.sh"
fi
sed "s|\${HEADROOM_REPO:-\$HOME/headroom}|$REPO_DIR|g" \
    "$CONTRIB/statusline-with-cache.sh" > "$CLAUDE_DIR/statusline-with-cache.sh"
chmod 755 "$CLAUDE_DIR/statusline-with-cache.sh"

if command -v node >/dev/null 2>&1; then
    [ -f "$SETTINGS" ] && cp "$SETTINGS" "$SETTINGS.bak"
    node -e '
const fs = require("fs");
const [file, cmd] = process.argv.slice(1);
let settings = {};
try { settings = JSON.parse(fs.readFileSync(file, "utf8")); } catch (e) {}
settings.statusLine = { type: "command", command: cmd };
fs.writeFileSync(file, JSON.stringify(settings, null, 2) + "\n");
' "$SETTINGS" "$CLAUDE_DIR/statusline-with-cache.sh"
    say "status line wired into $SETTINGS"
else
    say "node not found — set statusLine.command in $SETTINGS by hand:"
    say "  $CLAUDE_DIR/statusline-with-cache.sh"
fi

# ── done ──────────────────────────────────────────────────────────────────
step "Done"
say "Start Claude Code with:  cclaude"
say "Check it is working:     headroom doctor"
say "See what it saved:       headroom savings"
say ""
say "To go back: run 'claude' instead, and 'pkill -f headroom-proxy'."
