//! Byte-exact protection for file reads (`HEADROOM_PROTECT_READS`).
//!
//! Rust port of the read-protection helpers in
//! `headroom/transforms/content_router.py`.
//!
//! An agent that reads a file is about to patch it, and a patch needs the
//! exact bytes. Lossy-compressing a `cat`/`sed -n`/`head` output was observed
//! on SWE-bench and mini-swe-agent to make the agent re-read the same file
//! (`cat` -> `cat -A` -> `cat -n`) to recover the detail it lost — turn
//! inflation — and, when the recovery failed, to lose the resolve outright.
//!
//! Derived output stays compressible. `grep`, `ls`, `find` and a test run
//! describe a file rather than reproduce it, so nothing is patched from them.
//!
//! Two gates, in order:
//!
//! 1. [`is_read_command`] — the COMMAND says this is a file read.
//! 2. [`read_output_should_be_protected`] — the CONTENT is not confidently
//!    data. Protect by default and release only what is clearly a data type,
//!    because the code detector recognizes a handful of languages and gating
//!    on "is this source code" would leave Ruby, C and SQL — all seen as plain
//!    text — unprotected.
//!
//! Off by default. With the flag unset nothing here is consulted and the
//! dispatcher behaves exactly as it did before.

use std::collections::HashSet;
use std::sync::OnceLock;

use regex::Regex;
use serde_json::Value;

use super::content_detector::{detect_content_type, ContentType};
use super::content_router::bash_program;

/// Programs whose output is the file itself.
const READ_VERBS: &[&str] = &["cat", "head", "tail", "nl", "bat", "less", "more"];

/// Content types confidently DATA, released back to their own compressor.
///
/// `StructuredConfig` is deliberately absent: YAML, TOML and INI get patched
/// byte-for-byte like code does. Lockfiles are the carve-out, and they are
/// excluded by name in [`is_read_command`] rather than by type — they detect
/// as plain text, so the content gate would protect them.
const RELEASABLE_READ_TYPES: &[ContentType] = &[
    ContentType::JsonArray,
    ContentType::SearchResults,
    ContentType::BuildOutput,
    ContentType::GitDiff,
    ContentType::Html,
    ContentType::Tabular,
];

/// Machine-generated dependency lockfiles: the biggest and most repetitive
/// read in a session, regenerated by a tool and never patched by hand.
fn lockfile_re() -> &'static Regex {
    static RE: OnceLock<Regex> = OnceLock::new();
    RE.get_or_init(|| {
        Regex::new(
            r"(?i)(^|[\s/])(bun\.lock|bun\.lockb|package-lock\.json|npm-shrinkwrap\.json|\
             yarn\.lock|pnpm-lock\.yaml|uv\.lock|poetry\.lock|Pipfile\.lock|\
             requirements\.txt\.lock|Cargo\.lock|go\.sum|Gemfile\.lock|composer\.lock|\
             flake\.lock|Package\.resolved|gradle\.lockfile|packages\.lock\.json)(\s|$)",
        )
        .expect("LOCKFILE_RE is valid")
    })
}

/// A redirect, `tee` or heredoc anywhere in the command.
fn writes_a_file_re() -> &'static Regex {
    static RE: OnceLock<Regex> = OnceLock::new();
    RE.get_or_init(|| Regex::new(r"(^|\s)(>>?|tee\b|<<)").expect("write pattern is valid"))
}

/// `sed -n`, as its own token.
fn sed_quiet_re() -> &'static Regex {
    static RE: OnceLock<Regex> = OnceLock::new();
    RE.get_or_init(|| Regex::new(r"(^|\s)-n(\s|$)").expect("sed -n pattern is valid"))
}

/// Shells whose `-c` argument carries the command that actually runs.
fn nested_shells() -> &'static HashSet<&'static str> {
    static SHELLS: OnceLock<HashSet<&'static str>> = OnceLock::new();
    SHELLS.get_or_init(|| ["sh", "bash", "zsh", "dash"].iter().copied().collect())
}

/// True when `HEADROOM_PROTECT_READS` opts into byte-exact read protection.
///
/// Read from the environment on every call, like the other behavior flags in
/// this crate, so a process can be toggled without a restart. Every request
/// path consults this one function, so the flag means the same thing on the
/// Anthropic and the Responses side.
pub fn read_protection_enabled() -> bool {
    !matches!(
        std::env::var("HEADROOM_PROTECT_READS")
            .unwrap_or_default()
            .trim()
            .to_ascii_lowercase()
            .as_str(),
        "0" | "" | "false" | "no"
    )
}

/// Peel leading `cd <dir> &&` / `cd <dir>;` chains off a shell command.
///
/// Harnesses prefix nearly every command with `cd <repo> && ` to run in the
/// checkout. Without this the parsed program is `cd` rather than the real
/// tool, and read protection silently switches itself off for the agents that
/// need it most.
pub fn strip_cd_prefix(command: &str) -> String {
    static RE: OnceLock<Regex> = OnceLock::new();
    let re = RE.get_or_init(|| Regex::new(r"(?s)^cd\s+[^&;|]+(?:&&|;)\s*(.*)$").expect("valid"));
    let mut c = command.trim().to_string();
    while let Some(caps) = re.captures(&c) {
        c = caps[1].trim().to_string();
    }
    c
}

/// Extract the raw shell command from a tool call's arguments.
///
/// Anthropic's `input` is an object (`{"command": "cat f"}`), OpenAI's
/// `arguments` is a JSON string holding the same object, and Codex's shell
/// passes `command` as a list of tokens. Returns `""` for a non-shell tool.
///
/// Taking the parsed command matters: for OpenAI-style JSON-string arguments
/// the compact free-text form of the arguments is the raw `{"command": ...}`
/// JSON, on which [`is_read_command`] always answers false — which silently
/// disabled protection for every OpenAI-native harness.
pub fn tool_call_command_text(raw: &Value) -> String {
    let owned;
    let obj = match raw {
        Value::String(s) => match serde_json::from_str::<Value>(s) {
            Ok(v) => {
                owned = v;
                &owned
            }
            // Native local-shell calls may carry the command itself as a
            // string rather than a JSON-encoded arguments object.
            Err(_) => return s.clone(),
        },
        other => other,
    };
    let Some(map) = obj.as_object() else {
        return String::new();
    };
    let Some(cmd) = map.get("command").or_else(|| map.get("cmd")) else {
        return String::new();
    };
    match cmd {
        Value::String(s) => s.clone(),
        Value::Array(items) => items
            .iter()
            .map(|c| match c {
                Value::String(s) => s.clone(),
                other => other.to_string(),
            })
            .collect::<Vec<_>>()
            .join(" "),
        _ => String::new(),
    }
}

/// True when a shell command's output is raw file content the agent will
/// patch from — `cat`/`head`/`tail`/`nl`/`less`/`more` of a file, or `sed -n`
/// printing a range.
///
/// Writes are excluded: a redirect, a `tee` or a heredoc means the command
/// writes the file (`cat > f <<EOF`), and a bare `sed` without `-n` is a
/// stream edit.
///
/// This decides only that the command IS a read. Whether the read is actually
/// protected is settled by content in [`read_output_should_be_protected`].
/// The one command-level carve-out is the lockfile.
pub fn is_read_command(command: &str) -> bool {
    if command.is_empty() {
        return false;
    }
    let c = strip_cd_prefix(command);
    if writes_a_file_re().is_match(&c) {
        return false;
    }
    // The same structural parser the search-fold uses, so `sudo cat f`,
    // `timeout 30 cat f` and `rtk cat f` are all recognized rather than
    // dropped by a first-token match.
    let (prog, rest) = bash_program(&c);
    if prog.is_empty() {
        return false;
    }
    if nested_shells().contains(prog.as_str()) && !rest.is_empty() {
        // `bash -lc "cat …"` (Codex): the real command is the -c argument.
        for (j, tok) in rest.iter().enumerate() {
            if matches!(tok.as_str(), "-c" | "-lc" | "-lic" | "-ic") && j + 1 < rest.len() {
                let inner = rest[j + 1..].join(" ");
                return is_read_command(inner.trim_matches(['\'', '"']));
            }
        }
        return false;
    }
    let is_read = READ_VERBS.contains(&prog.as_str())
        // `sed -n '1,20p' file` prints a range; bare `sed` edits a stream.
        || (prog == "sed" && sed_quiet_re().is_match(&c));
    if !is_read {
        return false;
    }
    !lockfile_re().is_match(&c)
}

/// Finalize read protection by content — protect unless this is clearly data.
///
/// Detection failure protects, keeping the byte-exact default.
pub fn read_output_should_be_protected(text: &str) -> bool {
    if text.is_empty() {
        return false;
    }
    !RELEASABLE_READ_TYPES.contains(&detect_content_type(text).content_type)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn plain_file_reads_are_reads() {
        for c in [
            "cat src/main.rs",
            "head -50 src/main.rs",
            "tail -n 20 log.txt",
            "nl foo.py",
            "sed -n '1,20p' foo.py",
            "bat README.md",
        ] {
            assert!(is_read_command(c), "{c}");
        }
    }

    #[test]
    fn derived_output_stays_compressible() {
        for c in [
            "grep -rn foo src/",
            "rg pattern",
            "ls -la",
            "find . -name '*.py'",
            "pytest -q",
            // A stream edit, not a range print.
            "sed 's/a/b/' foo.py",
        ] {
            assert!(!is_read_command(c), "{c}");
        }
    }

    /// A redirect, a `tee` or a heredoc means the command writes the file.
    #[test]
    fn a_write_is_never_a_read() {
        for c in [
            "cat > f",
            "cat >> f",
            "cat f | tee g",
            "cat > f <<EOF",
            "head -1 a > b",
        ] {
            assert!(!is_read_command(c), "{c}");
        }
    }

    /// Harnesses prefix nearly every command with a `cd` into the checkout.
    #[test]
    fn a_cd_prefix_is_peeled_before_the_program_is_read() {
        assert_eq!(strip_cd_prefix("cd /repo && cat f"), "cat f");
        assert_eq!(strip_cd_prefix("cd /repo; cat f"), "cat f");
        assert_eq!(strip_cd_prefix("cd /a && cd /b && cat f"), "cat f");
        assert!(is_read_command("cd /repo && cat src/main.rs"));
        assert!(!is_read_command("cd /repo && grep -rn foo ."));
    }

    #[test]
    fn wrappers_and_nested_shells_are_seen_through() {
        assert!(is_read_command("sudo cat /etc/hosts"));
        assert!(is_read_command("timeout 30 cat f"));
        assert!(is_read_command("bash -lc \"cat src/main.rs\""));
        assert!(is_read_command("sh -c 'cd /repo && cat f'"));
        assert!(!is_read_command("bash -lc \"grep -rn foo .\""));
        // A shell with no -c runs a script, not a command we can classify.
        assert!(!is_read_command("bash script.sh"));
    }

    /// Lockfiles are regenerated by a tool, never patched by hand, and are the
    /// largest repetitive read in a session.
    #[test]
    fn a_lockfile_read_stays_compressible() {
        for c in [
            "cat package-lock.json",
            "cat Cargo.lock",
            "cat /repo/pnpm-lock.yaml",
            "head -100 go.sum",
        ] {
            assert!(!is_read_command(c), "{c}");
        }
        // The source file next to it is still protected.
        assert!(is_read_command("cat Cargo.toml"));
    }

    #[test]
    fn the_command_is_read_from_either_wire_shape() {
        // Anthropic: an object.
        assert_eq!(
            tool_call_command_text(&serde_json::json!({"command": "cat f"})),
            "cat f"
        );
        // OpenAI: a JSON string holding the object.
        assert_eq!(
            tool_call_command_text(&Value::String(r#"{"command": "cat f"}"#.into())),
            "cat f"
        );
        // Codex's shell: a token list.
        assert_eq!(
            tool_call_command_text(&serde_json::json!({"command": ["cat", "f"]})),
            "cat f"
        );
        // Native local shell string form.
        assert_eq!(
            tool_call_command_text(&Value::String("cat f".into())),
            "cat f"
        );
        // Non-shell tools and unparseable arguments yield nothing.
        assert_eq!(
            tool_call_command_text(&serde_json::json!({"file_path": "f"})),
            ""
        );
        assert_eq!(tool_call_command_text(&Value::Null), "");
    }

    /// Protect by default; release only what is confidently data. The code
    /// detector knows a handful of languages, so gating on "is this source
    /// code" would leave Ruby, C and SQL unprotected.
    #[test]
    fn unrecognized_code_is_protected_and_data_is_released() {
        // Ruby detects as plain text, and must still be protected.
        assert!(read_output_should_be_protected(
            "class Foo\n  def bar\n    @x = 1\n  end\nend\n"
        ));
        // A JSON array is data, and goes back to its own compressor.
        assert!(!read_output_should_be_protected(
            r#"[{"a": 1}, {"a": 2}, {"a": 3}]"#
        ));
        // So is a diff.
        assert!(!read_output_should_be_protected(
            "diff --git a/f.py b/f.py\n--- a/f.py\n+++ b/f.py\n@@ -1 +1 @@\n-old\n+new"
        ));
        // Empty output has nothing to protect.
        assert!(!read_output_should_be_protected(""));
    }

    /// YAML and TOML are patched byte-for-byte like code, so they are not on
    /// the released list even though they are structured.
    #[test]
    fn a_config_read_stays_protected() {
        assert!(read_output_should_be_protected(
            "name: build\non:\n  push:\n    branches: [main]\njobs:\n  test:\n    runs-on: ubuntu\n"
        ));
    }
}
